### PR TITLE
Add support for coco2 cartridges.

### PR DESCRIPTION
**Pull request by pezolt**
I don't have a blacklist file, but I've confirmed that this works with the handful of coco2 cartridges I tried with an attract screen.

### CODE REVIEW

**Comment by mrchrisster** [comment]
Hey pezolt, thanks for the commit. I just had some time to check the coco2 library and none of the games i tried had an attract mode. I also wasn't able to find a curated games pack for the system.
Those two things would be required to add the system to SAM. Hope you understand that I might not include the system.

**Comment by pezolt** [comment]
Ok... So, I can work through creating a list of cartridges that have an attract mode. 

Once I have the list, I can create a script that use wget/curl to pull them from the color computer archive: 

https://colorcomputerarchive.com/repo/Cartridges/

7 Card Stud (1983) (26-3074) (Intelligent Software LTD). ccc
Androne (1983) (26-3096) (Robert Arnstein) [!].ccc
Canyon Climber (1982) (26-3089) (DataSoft) [a1].ccc
Cave Hunter (1982) (Mark Data Products).ccc
Checker King (1980) (26-3055) (Personal Software).ccc
Clowns & Balloons (1982) (26-3087) (Steve Bjork) [!].ccc
Color Backgammon (1980) (26-3059) (Tandy).ccc
Color Baseball (1980) (26-3095) (Dale A. Lear) [!].ccc
Cyrus Chess (1982) (Dragon Data).ccc
Cyrus World Class Chess (1983) (26-3064) (Tandy).ccc
DON-PAN (1984) (26-3097) (Tandy).ccc
Demolition Derby (1984) (26-3044) (Spectral Associates) [!].ccc
Demon Attack (1984) (26-3099) (Activision).ccc
Doodle Bug (1982) (Computerware).ccc
Doubleback (1982) (26-3091) (Dale A. Lear) [!].ccc
Downland V1.1 (1983) (26-3046) (Tandy) [a1].ccc
Dragon Fire (1984) (26-3098) (Tandy).ccc
Dungeons of Daggorath (1982) (26-3093) (DynaMicro) [!].ccc
Football (1980) (26-3053) (Tandy) [!].ccc
...

**Comment by pezolt** [comment]
Here is a script to pull carts from the color computer archive that (mostly) have an attract mode (or drop you into the game): 

```
#!/bin/bash

carts=("https://colorcomputerarchive.com/repo/Cartridges/7%20Card%20Stud%20(1983)%20(26-3074)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Androne%20(1983)%20(26-3096)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Arkanoid%20(1987)%20(26-3043)%20(Tandy)%20(Coco%201-2%20version).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Canyon%20Climber%20(1982)%20(26-3089)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Clowns%20&%20Balloons%20(1982)%20(26-3087)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Color%20Baseball%20(1980)%20(26-3095)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Cyrus%20World%20Class%20Chess%20(1983)%20(26-3064)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/DON-PAN%20(1984)%20(26-3097)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Demolition%20Derby%20(1984)%20(26-3044)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Demon%20Attack%20(1984)%20(26-3099)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Doubleback%20(1982)%20(26-3091)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Downland%20v1.1%20(1983)%20(26-3046)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Dragon%20Fire%20(1984)%20(26-3098)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Dungeons%20of%20Daggorath%20(1982)%20(26-3093)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Mega-Bug%20(1982)%20(26-3076)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Monster%20Maze%20(1983)%20(26-3081)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Panic%20Button%20(1983)%20(26-3147)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Reactoid%20(1983)%20(26-3092)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Shooting%20Gallery%20(1982)%20(26-3088)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Silpheed%20(1988)%20(26-3054)%20(Tandy)%20(Coco%201-2%20version).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Soko-Ban%20(1988)%20(26-3161)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Starblaze%20(1983)%20(26-3094)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Stellar%20Lifeline%20(1983)%20(26-3047)%20(Tandy).ccc"
       "https://colorcomputerarchive.com/repo/Cartridges/Temple%20of%20ROM%20(1984)%20(26-3045)%20(Tandy).ccc"
)

for cart in "${carts[@]}";
do
    wget $cart
done
```

**Comment by pezolt** [comment]
I've been running with these games, and it (satisfying) flips between them.

Coco2 has another interesting quirk, where some games use joystick 2, and so you need to set the config option 'swap joystick' if you want to be able to press a button and start playing. 

I haven't yet figured out how tell the mgl how to do that... 
 
I think mister main just added something to make this possible, but I haven't figured it out yet... and have NO idea how to get MisterSAM to use it.

**Comment by mrchrisster** [comment]
Your script works well. Thanks! You can create custom mgls with different configs per game I believe but that wouldn't work with SAM..

**Pull request merged**
