### PR TITLE
TVC for  n64, atarilynx, atari2600, atari5200, atari7800, sgb, tgfx16, saturn,s32x, sms, gg, arcade

### PR DESCRIPTION
**Pull request by tallendorf**
Added samvideo tvc support for n64, atarilynx, atari2600, atari5200, atari7800, sgb, tgfx16, saturn,s32x, sms, gg, arcade

Videos for arcade, atari2600, atari5200, atari7800  have been made and can be uploaded to the archive (when and if it is up)

### CODE REVIEW

**Comment by mrchrisster** [comment]
Thanks Tallendorf, I'll take a look tomorrow!

**Comment by mrchrisster** [comment]
I still need to do some further testing but just encountered an error:
```
CPreloading Dig Dug Atari 2600 & 5200 1983.avi from archive.org for smooth playback
[#339020 0B/0B CN:1 DL:0B]                                                     
11/08 08:12:54 [ERROR] CUID#7 - Download aborted. URI=http://archive.org/download/640x480_videogame_commercials/Dig%20Dug%20Atari%202600%20&%205200%201983.avi
Exception: [AbstractCommand.cc:351] errorCode=22 URI=http://ia802708.us.archive.org/25/items/640x480_videogame_commercials/Dig%20Dug%20Atari%202600%20&%205200%201983.avi
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
No video was downloaded. Skipping video playback..
Starting now on the Atari 2600: Dig Dug (infinite lives) NTSC
 Next game in 172...
```

**Comment by tallendorf** [comment]
tvcs for arcade, atari2600, atari5200, atari7800  reference videos that are currently not on archive.org.   I have them but I didn't know the protocol for submitting the .avi.  Can we submit raw .avi files by themselves or does each one have to have a corresponding youtube link? Is there an enforced naming convention (most seem to follow one but not all)?

**Comment by mrchrisster** [comment]
The naming convention would be `SYSTEM-Title of commercial.avi`.
If you send these my way I'm happy to put them on archive. Thanks for your work on this!

**Comment by tallendorf** [comment]
Okay.  I will rename where appropriate, update the tvc names, and send a
link (but late tonight or tomorrow- busy day at work).

**Comment by mrchrisster** [comment]
Amazing thanks!

**Comment by tallendorf** [comment]
> Amazing thanks!
https://drive.google.com/drive/folders/1E7uZ3Pj8ZQUUJ3I7eB1AZ-VtGuK9bRRL?usp=sharing

**Comment by mrchrisster** [comment]
Sorry, archive doesn't allow upload atm, need to wait a bit before we can merge

**Comment by mrchrisster** [comment]
I'll merge for now and disable the cores that don't have videos yet

**Comment by tallendorf** [comment]
> Sorry, archive doesn't allow upload atm, need to wait a bit before we can merge

I think they're allowing uploads again (as of the 14th, so almost immediately after you wrote this).

**Comment by mrchrisster** [comment]
Great, it's all uploaded and updated. Can you test if the new code works for you?

**Comment by tallendorf** [comment]
There might be some issue with the corecount logic.
atari7800=1
atari2600=1
psx=196
atari5200=1
arcade=1
total_count=200
Changing PSX into Saturn yields:
atari7800=1
atari2600=1
saturn=1
atari5200=1
arcade=1
total_count=5

**Comment by tallendorf** [comment]
There is some weird issue where when it updated, it deletes the blacklist
and tvc in the .Mister_SAM/Sam_Gamelists/   Then they get loaded into /tmp
and then it just busy loops in the Mister_SAM_on.sh saying "I can't find
 #####_tvc.txt" and goes to next core.

I nuked all the intermediate folders and started over with Mister_SAM_on.h
and it has similar issues.
I'll look at it more tonight after work.

-Todd

**Comment by tallendorf** [comment]
The debug log implies the script maybe corrupted some how.  I copied a new
version from Github and the debug log looks an unclosed quote or something.

===
Local size: 0
samvideo corelist: atari7800 atari2600 saturn atari5200 arcade
Starting pick_core with array: atari7800 atari2600 saturn atari5200 arcade
Loading core counts from /tmp/.SAM_tmp/sv_corecount
Selected core: arcade based on pick value 32
nextcore = arcade
arcade_tvc.txt found.
URL is not available: Gauntlet (Rev 14)\|Gauntlet II.mra. Retrying...
arcade_tvc.txt found.
URL is not available: Gauntlet (Rev 14)\|Gauntlet II.mra. Retrying...
arcade_tvc.txt found.
URL is not available: Gauntlet (Rev 14)\|Gauntlet II.mra. Retrying...
arcade_tvc.txt found.
====

All the videos I already have downloaded in my /media/fat/videos/ and I'm
using "archive" mode.

**Comment by mrchrisster** [comment]
Should be fixed now
```
Initializing core counts for the first time
Found 30 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/nes_tvc.txt
Found 75 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/snes_tvc.txt
Found 16 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/tgfx16cd_tvc.txt
Found 4 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/saturn_tvc.txt
Found 4 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/s32x_tvc.txt
Found 196 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/psx_tvc.txt
Found 14 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/megacd_tvc.txt
Found 3 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/sms_tvc.txt
Found 7 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/tgfx16_tvc.txt
Found 5 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/arcade_tvc.txt
Found 104 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/genesis_tvc.txt
Found 103 games in /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/n64_tvc.txt
Saved core counts to /tmp/.SAM_tmp/sv_corecount
Selected core: snes based on pick value 80```

**Pull request merged**
